language: php

php:
  - 5.4
  - 5.5

services:
  - mongodb

branches:
  only:
    - master
    - develop

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-source

before_script:
 - sudo apt-get install -y imagemagick
 - yes '' | pecl install imagick
 - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - ./.travis/run.sh

script:
 - vendor/bin/phpunit

notifications:
  email: false