language: php

php:
  - 5.5
  - 5.4

install:
  - composer self-update && composer --version
  - composer install --dev --prefer-source

script:
 - vendor/bin/phpunit --coverage-clover=coverage.clover

before_script:
 - sudo apt-get install imagemagick
 - pecl install imagick
 - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover