language: php

matrix:
  fast_finish: true
  include:
  - php: 5.5
  - php: 5.6
  - php: 7
  - php: hhvm
  allow_failures:
  - php: 7
  - php: hhvm
  
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"  
  
cache:
  directories:
  - "$HOME/.composer/cache"

services:
  - mongodb

branches:
  only:
    - master
    - develop

install:
  - composer self-update && composer --version
  - composer update --prefer-source $DEPENDENCIES

before_script:
 - sudo apt-get install -y imagemagick
 - yes '' | pecl install imagick
 - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - ./.travis/run.sh
 - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

notifications:
  email: ripaclub@gmail.com