language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mongodb

branches:
  only:
    - master
    - develop

install:
  - composer self-update && composer --version
  - composer install --dev

before_script:
 - sudo apt-get install -y imagemagick
 - yes '' | pecl install imagick
 - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - ./.travis/run.sh
 - mkdir -p build/coverage

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls

notifications:
  email: ripaclub@gmail.com